### ISSUE TITLE
Reference file property `mapping_documentaion_url` appears to be mis-spelled ('mapping_documentation_url')

### ISSUE THREAD

**Issue by sgchoe** [CBIIT/c3dc-model#17]
Hi, there appears to be a typo in the name of the reference file object's 'mapping_documentaion_url' field, which I assume was meant to be spelled 'mapping_documentation_url'.

**Comment by svburke** [comment]
Thank you for catching that.

Fixed: https://github.com/CBIIT/c3dc-model/pull/19
