### ISSUE TITLE
Reference file object filed 'reference_file_id' not defined in model properties file

### ISSUE THREAD

**Issue by sgchoe** [CBIIT/c3dc-model#18]
Hi, the reference file object's [reference_file_id](https://github.com/CBIIT/c3dc-model/blob/8ba98a634ffc44a12cf5563d38e32bf8097ad306/model-desc/c3dc-model.yml#L60) field isn't defined in the [c3dc-model-props.yml file](https://github.com/CBIIT/c3dc-model/blob/main/model-desc/c3dc-model-props.yml).

**Comment by svburke** [comment]
Thank you for catching that.

Fixed: https://github.com/CBIIT/c3dc-model/pull/20
