### ISSUE TITLE
Add permissible value for survival.first_event

### ISSUE THREAD

**Issue by bfurner** [CBIIT/c3dc-model#98]
The following permissible value exists in the CDE, but hasn't yet been included in the C3DC schema definition for `survival.first_event`. Please add the following:

- "Induction Failure"

**Comment by bfurner** [comment]
Here is a [link to the CDE](https://cadsr.cancer.gov/onedata/dmdirect/NIH/NCI/CO/CDEDD?filter=CDEDD.ITEM_ID=3070936%20and%20ver_nr=2)

**Comment by dunnpa** [comment]
https://github.com/CBIIT/c3dc-model/blob/main/model-desc/c3dc-model-props.yml has additions

**Comment by dunnpa** [comment]
done
