### ISSUE TITLE
Add permissible values for genetic_analysis.alteration

### ISSUE THREAD

**Issue by bfurner** [CBIIT/c3dc-model#99]
The following permissible values exist in the CDE, but haven't yet been included in the C3DC schema definition for `genetic_analysis.alteration`. Please add the following:

- "BCR-ABL1 Fusion"
- "del(5q)"
- "del(7q)"
- "del(9q)"
- "inv(16)""
- "KIT Exon 8 Mutation"
- "KIT Exon 17 Mutation"
- "Loss of chromosome Y (LOY)"
- "Monosomy X"
- "TCF3-PBX1 Fusion"
- "Trisomy 21"

**Comment by bfurner** [comment]
Here is a [link to the CDE](https://cadsr.cancer.gov/onedata/dmdirect/NIH/NCI/CO/CDEDD?filter=CDEDD.ITEM_ID=13362278%20and%20ver_nr=1)

**Comment by dunnpa** [comment]
https://github.com/CBIIT/c3dc-model/blob/main/model-desc/c3dc-model-props.yml has additions

**Comment by dunnpa** [comment]
done
